In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data= pd.read_excel('/Users/ncc1031a/Documents/VSCode/MachineLearning/0320/ecodata.xlsx')
data=data.values        #转化为数组
area=data[:,:1]
data=data[:,1:]         #舍弃第一列
dataMat=data
data = np.array(data, dtype='float64')
np.set_printoptions(suppress=True,precision=2)
print('原始数据:\n',data)

原始数据:
 [[1394.89 2505.    519.01 8144.    373.9   117.3   112.6   843.43]
 [ 920.11 2720.    345.46 6501.    342.8   115.2   110.6   582.51]
 [2849.52 1258.    704.87 4839.   2033.3   115.2   115.8  1234.85]
 [1092.48 1250.    290.9  4721.    717.3   116.9   115.6   697.25]
 [ 832.88 1387.    250.23 4134.    781.7   117.5   116.8   419.39]
 [2793.37 2397.    387.99 4911.   1371.1   116.1   114.   1840.55]
 [1129.2  1872.    320.45 4430.    497.4   115.2   114.2   762.47]
 [2014.53 2334.    435.73 4145.    824.8   116.1   114.3  1240.37]
 [2462.57 5343.    996.48 9279.    207.4   118.7   113.   1642.95]
 [5155.25 1926.   1434.95 5934.   1025.5   115.8   114.3  2026.64]
 [3524.79 2249.   1006.39 6619.    754.4   116.6   113.5   916.59]
 [2003.58 1254.    474.   4609.    908.3   114.8   112.7   824.14]
 [2160.52 2320.    553.97 5857.    609.3   115.2   114.4   433.67]
 [1205.1  1182.    282.84 4211.    411.7   116.9   115.9   571.84]
 [5002.34 1527.   1229.55 5145.   1196.6   117.6   114.

In [8]:
##填空
temp = np.std(data, axis=0)
##填空
data -= np.mean(data, axis=0)
data /= temp
normData=data
##填空
data = np.cov(data.T)
print('协方差矩阵:\n',data)

协方差矩阵:
 [[ 1.14  1.01  1.13  0.92  0.99 -1.13 -1.08  1.14]
 [ 1.01  1.14  1.06  1.13  0.6  -1.09 -1.13  0.99]
 [ 1.13  1.06  1.14  0.99  0.92 -1.14 -1.12  1.13]
 [ 0.92  1.13  0.99  1.14  0.45 -1.02 -1.09  0.89]
 [ 0.99  0.6   0.92  0.45  1.14 -0.88 -0.75  1.01]
 [-1.13 -1.09 -1.14 -1.02 -0.88  1.14  1.13 -1.12]
 [-1.08 -1.13 -1.12 -1.09 -0.75  1.13  1.14 -1.07]
 [ 1.14  0.99  1.13  0.89  1.01 -1.12 -1.07  1.14]]


In [22]:
##填空
eigValue,eigVec = np.linalg.eigh(data)
##填空
idx = np.argsort(eigValue)[::-1]
selectVec = eigVec[:,idx]
selectValue = eigValue[idx]
components = selectVec[:,:3]
X_reduced = np.dot(normData,components)
X_reduced

array([[-1.92, -0.48, -0.  ],
       [-1.54,  1.14,  0.  ],
       [-2.04, -0.1 , -0.  ],
       [-1.1 ,  1.49,  0.  ],
       [-0.72, -1.48,  0.  ],
       [ 4.66,  0.29, -0.  ],
       [ 4.51, -0.27,  0.  ],
       [-1.86, -0.59, -0.  ]])

In [23]:
components

array([[-0.37, -0.18, -0.46],
       [-0.35,  0.36,  0.3 ],
       [-0.37, -0.05, -0.47],
       [-0.33,  0.51, -0.13],
       [-0.29, -0.7 ,  0.37],
       [ 0.37, -0.01, -0.43],
       [ 0.37, -0.19, -0.28],
       [-0.37, -0.22, -0.24]])

In [24]:
contri = selectValue/np.sum(selectValue)
cumcontri = np.cumsum(contri)

In [25]:
np.cumsum(contri)

array([0.9, 1. , 1. , 1. , 1. , 1. , 1. , 1. ])

## 使用sklearn对normData实现PCA降维
from sklearn.decomposition import PCA
pcs = PCA()
## 填空，拟合
pcs.________
  

In [26]:
##填空，显示所有主成分
total_var = np.sum(selectValue)
var_ratio = selectValue / total_var
cum_var_ratio = np.cumsum(var_ratio)

print("特征值:\n", selectValue)
print("\n解释方差比例:\n", var_ratio)
print("\n累积解释方差比例:\n", cum_var_ratio)
print("\n特征向量(主成分):\n", selectVec)

特征值:
 [ 8.22  0.93  0.    0.    0.    0.   -0.   -0.  ]

解释方差比例:
 [ 0.9  0.1  0.   0.   0.   0.  -0.  -0. ]

累积解释方差比例:
 [0.9 1.  1.  1.  1.  1.  1.  1. ]

特征向量(主成分):
 [[-0.37 -0.18 -0.46 -0.12  0.19 -0.13  0.18  0.72]
 [-0.35  0.36  0.3   0.61  0.24 -0.27 -0.35  0.18]
 [-0.37 -0.05 -0.47 -0.17  0.28 -0.33 -0.25 -0.6 ]
 [-0.33  0.51 -0.13 -0.32 -0.6   0.2  -0.32  0.09]
 [-0.29 -0.7   0.37 -0.07 -0.37 -0.21 -0.31  0.04]
 [ 0.37 -0.01 -0.43  0.42 -0.51 -0.49  0.01  0.02]
 [ 0.37 -0.19 -0.28  0.08  0.2   0.38 -0.73  0.17]
 [-0.37 -0.22 -0.24  0.55 -0.18  0.58  0.23 -0.21]]


In [ ]:
##填空，显示主成分方差值占比
_____________

In [ ]:
## 填空，显示累计主成分方差值占比


In [29]:
import numpy as np

A = np.array([[0,1],[1,1],[1,0]])
U,Sigma,VT = np.linalg.svd(A,full_matrices=True)
print('U',U)
print('Sigma',Sigma)
print('VT',VT)

U [[-0.41  0.71  0.58]
 [-0.82  0.   -0.58]
 [-0.41 -0.71  0.58]]
Sigma [1.73 1.  ]
VT [[-0.71 -0.71]
 [-0.71  0.71]]


In [31]:
np.dot(U[:,:2]*Sigma,VT)

array([[ 0.,  1.],
       [ 1.,  1.],
       [ 1., -0.]])

In [32]:
import numpy as np
dd = np.array([[0,0,1,1,0,0,0,0,0],
               [0,0,0,0,0,1,0,0,1],
               [0,1,0,0,0,0,0,1,0],
               [0,0,0,0,0,0,1,0,1],
               [1,0,0,0,0,1,0,0,0],
               [1,1,1,1,1,1,1,1,1],
               [1,0,1,0,0,0,0,0,0],
               [0,0,0,0,0,0,1,0,1],
               [0,0,0,0,0,2,0,0,1],
               [1,0,1,0,0,0,0,1,0],
               [0,0,0,1,1,0,0,0,0]])

In [33]:
U,sigma,  VT = np.linalg.svd(dd)

In [34]:
print(U[:,:3])

[[-0.15  0.27 -0.04]
 [-0.24 -0.38  0.09]
 [-0.13  0.17 -0.07]
 [-0.18 -0.19 -0.45]
 [-0.22 -0.09  0.46]
 [-0.74  0.21 -0.21]
 [-0.18  0.3   0.28]
 [-0.18 -0.19 -0.45]
 [-0.36 -0.59  0.34]
 [-0.25  0.42  0.28]
 [-0.12  0.14 -0.23]]


In [35]:
sigma

array([3.91, 2.61, 2.  , 1.69, 1.55, 1.04, 0.59, 0.41, 0.27])

In [36]:
sig2 = sigma**2
np.sum(sig2)


np.float64(32.99999999999999)

In [37]:
np.sum(sig2[:4])/np.sum(sig2)

np.float64(0.8764977299308567)

In [38]:
import numpy as np

X = np.array([[1,5,6],[4,3,9],[4,2,9], [4,2,2]])


In [39]:
np.cov(X)

array([[ 7.  ,  4.5 ,  4.  , -3.  ],
       [ 4.5 , 10.33, 11.5 , -1.33],
       [ 4.  , 11.5 , 13.  , -1.  ],
       [-3.  , -1.33, -1.  ,  1.33]])

In [40]:
from sklearn import preprocessing
X=[[1.,-1,2],[2,0,0],[0,1,-1]]
X_norm = preprocessing.normalize(X,norm='l2')
X_norm

array([[ 0.41, -0.41,  0.82],
       [ 1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.71, -0.71]])

In [41]:
np.dot(X_norm[1],X_norm[1])

np.float64(1.0)